;;; use-package-ensure-system-package+-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "use-package-ensure-system-package+" "use-package-ensure-system-package+.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from use-package-ensure-system-package+.el

(autoload 'upesp+:use-package-ensure-system-package-consify "use-package-ensure-system-package+" "\
Turn ARG into a cons of the form (PACKAGE-NAME . INSTALL-COMMAND').
Replaced async-shell-command to upesp+:async-shell-command
to prevent to run package manager at the same time.

\(fn ARG)")

(advice-add 'use-package-ensure-system-package-consify :filter-return #'upesp+:use-package-ensure-system-package-consify)

(register-definition-prefixes "use-package-ensure-system-package+" '("upesp+:"))

;;;***

;;; End of scraped data

(provide 'use-package-ensure-system-package+-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; use-package-ensure-system-package+-autoloads.el ends here
